feat: update enum for subsidy reference type to inclue a SF OpportunityLineItem
openedx/enterprise-subsidy pull request #48
Opened 2023-04-03 18:34 UTC by pwnage101

We have been informed that this is the correct object in salesforce to use as a subsidy reference.

2023-04-03 18:53 UTC, iloveagent57 requested changes

2023-04-03 18:53 UTC, iloveagent57 commented on enterprise_subsidy/apps/subsidy/models.py
> +    OPPORTUNITY_LINE_ITEM = "salesforce_OpportunityLineItem"
nit: we should snake-case this value to make it consistent with how we typically define the persisted value of choices.

2023-04-04 15:30 UTC, pwnage101 commented
* removed outdated comment
* prefixed enum key with `SALESFORCE_` to be more explicit
* made db value fully snake_case

2023-04-04 16:54 UTC, iloveagent57 approved these changes

2023-04-04 19:46 UTC, merged